launguage: cpp
dist: trusty
sudo: require
os: linux
compiler: gcc

before_install:
  - sudo apt-get install -qq valgrind

compiler:
  - g++
  - clang

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ./BinaryTree
    - ./BinaryTree-ut
    - valgrind --leak-check=full --show-leak-kinds=all -v ./BinaryTree
